# Generated by Django 3.1.2 on 2021-08-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='link',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='link_github',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='link_medium',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='link_website',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
