# Generated by Django 3.1.2 on 2021-07-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='institut',
            new_name='img',
        ),
        migrations.AddField(
            model_name='study',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
