# Generated by Django 2.0.2 on 2021-07-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0002_auto_20210718_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='category',
        ),
    ]
