# Generated by Django 3.1.2 on 2021-07-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0002_auto_20210727_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='name',
            new_name='school_name',
        ),
    ]
