# Generated by Django 3.1.2 on 2021-08-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0002_auto_20210803_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='core_skill',
            field=models.BooleanField(default=False),
        ),
    ]
