# Generated by Django 2.0.2 on 2021-07-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0003_remove_publication_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Subcategory',
            new_name='subcategory',
        ),
    ]
