# Generated by Django 3.1.2 on 2021-08-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0003_skill_core_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(to='mycv.Skill'),
        ),
    ]
