# Generated by Django 3.1.2 on 2021-07-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0003_auto_20210727_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
