# Generated by Django 2.0.2 on 2021-07-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0004_auto_20210718_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='Author',
            new_name='author',
        ),
    ]
