# Generated by Django 3.1.2 on 2021-07-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0004_study_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(choices=[('linkedin', 'linkedin'), ('twitter', 'twitter'), ('github', 'github'), ('medium', 'medium')], max_length=100)),
                ('link', models.CharField(max_length=500, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycv.profile')),
            ],
        ),
    ]
