# Generated by Django 3.1.2 on 2021-08-02 16:33

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0005_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('project_title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=100)),
                ('link_website', models.CharField(max_length=1000, null=True)),
                ('link_github', models.CharField(max_length=1000, null=True)),
                ('link_medium', models.CharField(max_length=1000, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycv.profile')),
                ('skills', models.ManyToManyField(to='mycv.Skill')),
            ],
        ),
    ]
