# Generated by Django 3.1.2 on 2021-08-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0006_auto_20210804_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
